apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-connection-deployment
  namespace: db-connection
spec:
  replicas: 2
  selector:
    matchLabels:
      service: db-connection-service
  template:
    metadata:
      labels:
        app: db-connection-service
    spec:
      containers:
      - name: db-connection
        image: your-registry/service1:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          value: <your-access-key>
        - name: AWS_SECRET_ACCESS_KEY
          value: <your-secret-key>
        ports:
        - containerPort: 8080
